# ===============================
# IDENTIFICACI\u00d3N DEL SERVICIO
# ===============================
spring.application.name=postventa-service
server.port=8082

# ===============================
# CONEXIÓN A LA BASE DE DATOS (NEON DB)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-lively-credit-atd7uhzf.c-9.us-east-1.aws.neon.tech/postventa_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_r45fIbmaJLxw
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACI\u00d3N DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURACIÓN FEIGN
# ===============================
spring.cloud.openfeign.lazy-resolution=true

# ===============================
# ANALYTICS SERVICE
# ===============================
analytics.service.url=http://localhost:3003
analytics.api.key=sk-analytics-dev-secret
