# ===============================
# IDENTIFICACI\u00d3N DEL SERVICIO
# ===============================
spring.application.name=postventa-service
server.port=8082

# ===============================
# CONEXI\u00c3\u0093N A LA BASE DE DATOS (NEON DB)
# ===============================
spring.datasource.url=jdbc:postgresql://ep-lively-credit-atd7uhzf.c-9.us-east-1.aws.neon.tech/postventa_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_r45fIbmaJLxw
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# CONFIGURACI\u00d3N DE JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# CONFIGURACI\u00d3N FEIGN
# ===============================
spring.cloud.openfeign.lazy-resolution=true

# URL del servicio de ordenes (local: http://localhost:8081/api/v1/ordenes, Railway: https://backend-servicio-ordenes-production.up.railway.app/api/v1/ordenes)
ordenes.service.url=https://backend-servicio-ordenes-production.up.railway.app/api/v1/ordenes

# ===============================
# ANALYTICS SERVICE
# ===============================
analytics.service.url=https://analytics-service-production-0f6a.up.railway.app
analytics.api.key=W0]MDr!d,s(9A=cQ.1

# ===============================
# CATALOG SERVICE
# ===============================
catalog.service.url=https://catalog-service-production-58a6.up.railway.app

# ===============================
# VENDOR SERVICE
# ===============================
vendor.service.url=https://vendor-service-9wfb.onrender.com
